### PR TITLE
Fix netstat build error

### PR DESCRIPTION
**Pull request by hulto**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes libc compile error by replacing deprecated library netstat2 with listeners

#### Which issue(s) this PR fixes:
Fixes #

### CODE REVIEW

**Comment by hulto** [comment]
GLIBC version:
```
ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35
```

**Comment by hulto** [comment]
```
apt update && apt install -y curl git vim
curl --tlsv1.2 https://sh.rustup.rs -sSf | bash -s -- -y --no-modify-path --profile minimal 2>&1
. "$HOME/.cargo/env" 
rustup update
git clone https://github.com/spellshift/realm.git
cd realm/implants/
apt install -y make
cargo build

   Compiling netstat2 v0.9.1
error[E0609]: no field `state` on type `&libc::tcp_info`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/netstat2-0.9.1/src/integrations/linux/netlink_iterator.rs:193:40
    |
193 |             return TcpState::from(tcpi.state);
    |                                        ^^^^^ unknown field
    |
    = note: available fields are: `tcpi_state`, `tcpi_ca_state`, `tcpi_retransmits`, `tcpi_probes`, `tcpi_backoff` ... and 26 others

For more information about this error, try `rustc --explain E0609`.
error: could not compile `netstat2` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

```

**Comment by hulto** [comment]
The github action image: `ubuntu-2004` has to new of a version of ldd

**Comment by hulto** [comment]
I think we should remove netstat2 as a dependency and replace it with something else or implement our own.
Does not seem worthwhile to quick fix the CI by pinning an older version of `ldd`

**Review by jabbate19 — APPROVED** [review]
:shipit:

**Pull request merged**
